export const REASONING_TYPE_PATTERNS = {
  'Data Retrieval': [/\bSELECT\b[\s\S]{0,200}?\bFROM\b/i],
  'Data Manipulation': [/\b(?:INSERT\s+INTO|UPDATE\s+\w|DELETE\s+FROM|MERGE\s+INTO)\b/i],
  'Control Flow': [/\b(?:IF\b[\s\S]{0,120}?\bTHEN\b|CASE\b[\s\S]{0,120}?\bWHEN\b)/i],
  Iterative: [/\b(?:FOR\s+\w+\s+IN\b|WHILE\b[\s\S]{0,80}?LOOP\b|(?:^|\s)LOOP\b)/i],
  'Transaction Management': [/\b(?:COMMIT|ROLLBACK|SAVEPOINT|SET\s+TRANSACTION)\b/i],
  'Dynamic SQL': [/\b(?:EXECUTE\s+IMMEDIATE|DBMS_SQL|OPEN\s+\w+\s+FOR)\b/i],
  'Exception Handling': [/\bEXCEPTION\b[\s\S]{0,100}?\bWHEN\b/i],
  'Event-Driven Logic': [/\bCREATE\s+(?:OR\s+REPLACE\s+)?TRIGGER\b/i],
  Cursors: [/\b(?:CURSOR\s+\w+\s+IS|OPEN\s+\w+\b|FETCH\s+\w+\s+INTO|CLOSE\s+\w+\b)\b/i],
  Debugging: [/\b(?:DBMS_OUTPUT\.PUT_LINE|SQLERRM|SQLCODE)\b/i],
  'Object-Oriented Design': [/\b(?:CREATE\s+(?:OR\s+REPLACE\s+)?TYPE\s+\w+\s+AS\s+OBJECT|MEMBER\s+(?:FUNCTION|PROCEDURE))\b/i],
  Encapsulation: [/\bCREATE\s+(?:OR\s+REPLACE\s+)?PACKAGE(?:\s+BODY)?\b/i],
  'Root Cause Analysis': [/\bDBMS_OUTPUT\.PUT_LINE\b/i, /--\s*RCA/i],
  Collections: [/\b(?:BULK\s+COLLECT\s+INTO|FORALL\b|TYPE\s+\w+\s+IS\s+(?:TABLE|VARRAY)|\.(?:EXTEND|TRIM|DELETE|COUNT|FIRST|LAST)\b)\b/i],
  Validation: [/\b(?:BETWEEN|RAISE_APPLICATION_ERROR|IF\b[\s\S]{0,200}?\bIS\s+NULL)\b/i],
  Aggregation: [/\b(?:COUNT|SUM|AVG|MIN|MAX|LISTAGG)\s*\(/i],
  'Inline execution': [/\b(?:EXISTS\s*\(|TABLE\s*\(|FROM\s*\(\s*SELECT|PRAGMA\s+AUTONOMOUS_TRANSACTION)\b/i],
  'Memory & Type': [/\b(?:%TYPE|%ROWTYPE|TYPE\s+\w+\s+IS\s+RECORD)\b/i],
};

export const PLSQL_CONSTRUCT_PATTERNS = {
  'CREATE OR REPLACE PROCEDURE': /\bCREATE\s+OR\s+REPLACE\s+PROCEDURE\b/i,
  'CREATE OR REPLACE FUNCTION': /\bCREATE\s+OR\s+REPLACE\s+FUNCTION\b/i,
  'CREATE OR REPLACE PACKAGE': /\bCREATE\s+OR\s+REPLACE\s+PACKAGE\b(?!\s+BODY)/i,
  'CREATE OR REPLACE PACKAGE BODY': /\bCREATE\s+OR\s+REPLACE\s+PACKAGE\s+BODY\b/i,
  'CREATE OR REPLACE TRIGGER': /\bCREATE\s+OR\s+REPLACE\s+TRIGGER\b/i,
  'CREATE TYPE ... AS OBJECT( ... )': /\bCREATE\s+(?:OR\s+REPLACE\s+)?TYPE\b[\s\S]{0,200}?\bAS\s+OBJECT\s*\(/i,
  'CREATE TYPE ... AS TABLE OF ...': /\bCREATE\s+(?:OR\s+REPLACE\s+)?TYPE\b[\s\S]{0,200}?\bAS\s+TABLE\s+OF\b/i,
  'MEMBER FUNCTION ... RETURN ...': /\bMEMBER\s+FUNCTION\b[\s\S]{0,120}?\bRETURN\b/i,
  'IF ... THEN ... END IF': /\bIF\b[\s\S]{0,300}?\bTHEN\b[\s\S]{0,300}?\bEND\s+IF\b/i,
  'CASE': /\bCASE\b[\s\S]{0,200}?\bWHEN\b/i,
  'LOOP ... END LOOP': /\bLOOP\b[\s\S]{0,300}?\bEND\s+LOOP\b/i,
  'FOR ... IN ... LOOP ... END LOOP': /\bFOR\s+\w+\s+IN\b[\s\S]{0,300}?\bLOOP\b[\s\S]{0,300}?\bEND\s+LOOP\b/i,
  'WHILE ... LOOP ... END LOOP': /\bWHILE\b[\s\S]{0,200}?\bLOOP\b[\s\S]{0,300}?\bEND\s+LOOP\b/i,
  'EXECUTE IMMEDIATE ...': /\bEXECUTE\s+IMMEDIATE\b/i,
  'EXECUTE IMMEDIATE ... USING': /\bEXECUTE\s+IMMEDIATE\b[\s\S]{0,200}?\bUSING\b/i,
  'EXECUTE IMMEDIATE ... INTO': /\bEXECUTE\s+IMMEDIATE\b[\s\S]{0,200}?\bINTO\b/i,
  'DECLARE ... BEGIN ... END': /\bDECLARE\b[\s\S]{0,500}?\bBEGIN\b[\s\S]{0,1000}?\bEND\b/i,
  'SELECT ... INTO ... FROM ...': /\bSELECT\b[\s\S]{0,200}?\bINTO\b[\s\S]{0,200}?\bFROM\b/i,
  INSERT: /\bINSERT\s+INTO\b/i,
  UPDATE: /\bUPDATE\b/i,
  DELETE: /\bDELETE\s+FROM\b/i,
  COMMIT: /\bCOMMIT\b/i,
  ROLLBACK: /\bROLLBACK\b/i,
  SAVEPOINT: /\bSAVEPOINT\b/i,
  'BULK COLLECT INTO': /\bBULK\s+COLLECT\s+INTO\b/i,
  'FORALL ... IN ...': /\bFORALL\b[\s\S]{0,120}?\bIN\b/i,
  'CURSOR ... IS ...': /\bCURSOR\s+\w+\s+IS\b/i,
  OPEN: /\bOPEN\s+\w+\b/i,
  FETCH: /\bFETCH\s+\w+\s+INTO\b/i,
  CLOSE: /\bCLOSE\s+\w+\b/i,
  RETURN: /\bRETURN\b/i,
  RETURNING: /\bRETURNING\b/i,
  'PRAGMA AUTONOMOUS_TRANSACTION': /\bPRAGMA\s+AUTONOMOUS_TRANSACTION\b/i,
  '%TYPE': /\b%TYPE\b/i,
  '%ROWTYPE': /\b%ROWTYPE\b/i,
  EXISTS: /\bEXISTS\s*\(/i,
  COUNT: /\bCOUNT\s*\(/i,
  LIMIT: /\bLIMIT\b/i,
  FIRST: /\bFIRST\b/i,
  LAST: /\bLAST\b/i,
  EXTEND: /\bEXTEND\b/i,
  TRIM: /\bTRIM\b/i,
  'TYPE ... IS RECORD ...': /\bTYPE\s+\w+\s+IS\s+RECORD\b/i,
  'TYPE ... IS TABLE OF ...': /\bTYPE\s+\w+\s+IS\s+TABLE\s+OF\b/i,
  'TYPE ... IS VARRAY() OF ...': /\bTYPE\s+\w+\s+IS\s+VARRAY\s*\(/i,
  'EXCEPTION (declaration)': /\b[A-Z][A-Z0-9_$#]*\s+EXCEPTION\s*;/i,
  'EXCEPTION ... WHEN NO_DATA_FOUND THEN ...': /\bWHEN\s+NO_DATA_FOUND\s+THEN\b/i,
  'EXCEPTION ... WHEN OTHERS THEN ...': /\bWHEN\s+OTHERS\s+THEN\b/i,
  'RAISE_APPLICATION_ERROR ...': /\bRAISE_APPLICATION_ERROR\b/i,
  SQLCODE: /\bSQLCODE\b/i,
  SQLERRM: /\bSQLERRM\b/i,
  RAISE: /\bRAISE\b/i,
  'JOIN ... ON ...': /\b(?:INNER\s+|LEFT(?:\s+OUTER)?\s+|RIGHT(?:\s+OUTER)?\s+|FULL(?:\s+OUTER)?\s+)?JOIN\b[\s\S]{0,120}?\bON\b/i,
  'GROUP BY': /\bGROUP\s+BY\b/i,
  HAVING: /\bHAVING\b/i,
  LISTAGG: /\bLISTAGG\s*\(/i,
  SUM: /\bSUM\s*\(/i,
  AVG: /\bAVG\s*\(/i,
  MIN: /\bMIN\s*\(/i,
  MAX: /\bMAX\s*\(/i,
  'ROW_NUMBER()': /\bROW_NUMBER\s*\(/i,
  'RANK()': /\bRANK\s*\(/i,
  'DENSE_RANK()': /\bDENSE_RANK\s*\(/i,
  'LAG()': /\bLAG\s*\(/i,
  'LEAD()': /\bLEAD\s*\(/i,
  ROUND: /\bROUND\s*\(/i,
  'TABLE( ... )': /\bTABLE\s*\(/i,
  'REGEXP_LIKE': /\bREGEXP_LIKE\s*\(/i,
  'REGEXP_SUBSTR': /\bREGEXP_SUBSTR\s*\(/i,
  BETWEEN: /\bBETWEEN\b/i,
  LIKE: /\bLIKE\b/i,
  'UNION ALL': /\bUNION\s+ALL\b/i,
  UNION: /\bUNION\b/i,
  DISTINCT: /\bDISTINCT\b/i,
  'ORDER BY': /\bORDER\s+BY\b/i,
};

export const REQUIRED_PUBLISH_FIELDS = [
  'user',
  'tables',
  'columns',
  'referenceAnswer',
  'testCases',
  'reasoningTypes',
  'plSqlConstructs',
];
